<html>
<head>
<?php html_header_show();?>
<link rel="stylesheet" href="<?php echo $GLOBALS['css_header'];?>" type="text/css">
<link media="all" type="text/css" href="http://code.jquery.com/ui/1.8.24/themes/base/jquery-ui.css" rel="stylesheet">
<link media="all" type="text/css" href="http://static.jquery.com/ui/css/demo-docs-theme/ui.theme.css" rel="stylesheet">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.8.24/jquery-ui.min.js"></script>
<style type="text/css">
.element .label {
    font-style: bold;
    float: left;   
}

.element .label {
    float: left;   
}
</style>
</head>
<body class="body_top">
<?php echo $this->layout()->content; ?>
</body>
</html>

