<?php
 // Copyright (C) 2010-2011 Aron Racho <aron@mi-squred.com>
 //
 // This program is free software; you can redistribute it and/or
 // modify it under the terms of the GNU General Public License
 // as published by the Free Software Foundation; either version 2
 // of the License, or (at your option) any later version.
?>
<html>
<head>
    <?php html_header_show();?>
    <link rel="stylesheet" href="<?= $GLOBALS['css_header'] ?>" type="text/css">
    <script type="text/javascript" src="<?= $GLOBALS['webroot']; ?>/library/js/jquery.js"></script>

</head>

<body class='body_top'>

<?php echo $this->layout()->content; ?>


</body>

</html>
