
--
-- Table structure for table `gtc_action`
--

CREATE TABLE `gtc_action` (
  `action_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'unique identifier for action',
  `parent_id` bigint(20) NOT NULL COMMENT 'actions can generate other actions. this is the parent id of action, if it was generated by another action',
  `case_id` bigint(20) NOT NULL COMMENT 'reference to case_id in gtc_case',
  `action_type_id` bigint(20) NOT NULL COMMENT 'reference to gtc_action_type',
  `state_id` bigint(20) NOT NULL COMMENT 'current state of action, refers to gtc_state',
  `title` varchar(255) NOT NULL,
  `due_date` datetime DEFAULT NULL,
  `description` longtext,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`action_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_action_meta`
--

CREATE TABLE `gtc_action_meta` (
  `meta_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'unique id for meta element',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` varchar(255) DEFAULT NULL,
  `action_id` bigint(20) NOT NULL COMMENT 'reference to unique identifier for action type',
  `meta_key` varchar(255) NOT NULL COMMENT 'meta key, like days_till_due, or form_link, order, encounter id',
  `meta_value` longtext NOT NULL COMMENT 'meta value',
  PRIMARY KEY (`meta_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=49 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_action_type_meta`
--

CREATE TABLE `gtc_action_type_meta` (
  `meta_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'unique id for meta element',
  `action_type_id` bigint(20) NOT NULL COMMENT 'unique identifier for action type',
  `meta_key` varchar(255) NOT NULL,
  `meta_value` longtext NOT NULL,
  PRIMARY KEY (`meta_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_case`
--

CREATE TABLE `gtc_case` (
  `case_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'unique identifier for case',
  `client_id` bigint(20) NOT NULL COMMENT 'reference to patient_data pid in OpenEMR',
  `creator_id` bigint(20) NOT NULL COMMENT 'reference to user in users table, who created the case',
  `state_id` bigint(20) NOT NULL COMMENT 'current state of case, refers to gtc_state',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_case_meta`
--

CREATE TABLE `gtc_case_meta` (
  `meta_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'unique id for meta element',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` varchar(255) DEFAULT NULL,
  `case_id` bigint(20) NOT NULL COMMENT 'reference to unique identifier for case id',
  `meta_key` varchar(255) NOT NULL COMMENT 'meta key, like changed hands, case opened date, case closed date',
  `meta_value` longtext NOT NULL COMMENT 'meta value',
  PRIMARY KEY (`meta_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_case_owner`
--

CREATE TABLE `gtc_case_owner` (
  `owner_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `case_id` bigint(20) NOT NULL COMMENT 'refers to case_id in gtc_case',
  `group` varchar(255) NOT NULL DEFAULT '' COMMENT 'group name of owner if any',
  `user_id` bigint(20) DEFAULT '0' COMMENT 'user id of owner, if any',
  PRIMARY KEY (`owner_id`),
  KEY `case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_note`
--

CREATE TABLE `gtc_note` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `body` longtext,
  `pid` bigint(20) DEFAULT NULL,
  `case_id` bigint(20) DEFAULT NULL,
  `action_id` bigint(20) DEFAULT NULL,
  `reminder_date` datetime DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `assigned_to` varchar(255) DEFAULT NULL,
  `deleted` tinyint(4) DEFAULT '0' COMMENT 'flag indicates note is deleted',
  `message_status` varchar(20) NOT NULL DEFAULT 'New',
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `gtc_transition_event`
--

CREATE TABLE `gtc_transition_event` (
  `transition_event_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'unique identifier for transition event',
  `transition_id` bigint(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `options` longtext,
  PRIMARY KEY (`transition_event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
